[params]
# App Info
  ios_app_id = 1621328561
  ios_app_country = "us"
  appstore_link = ""
  playstore_link = ""
  presskit_download_link = "https://emilbaehr.com"
  app_icon = "/images/appstore.png"
  app_name = "test app_name"
  app_price = "test app_price"
  app_description = "Write a short tagline for your app."

  enable_smart_app_banner = true

  # Information About Yourself
  your_name = "Emil Baehr"
  your_link = "https://emilbaehr.com"
  your_city = "Copenhagen"
  email_address = "emil.baehr@gmail.com"
  facebook_username = "rgdfdfhfghgf"
  instagram_username = "ebaehr"
  twitter_username = "ebaehr"
  github_username = "emilbaehr"
  youtube_username = "aegfdhdf"
  mastodon_link = "https://mastodon.social/@ebaehr"

# Feature List

  features = [
    { title = "GitHub Pages Jekyll Theme", description = "Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voil√°!", fontawesome_icon_name = "magic" },
    { title = "iPhone Device Preview", description = "Preview your app in the context of an iPhone device. Five different device colors included.", fontawesome_icon_name = "mobile" },
    { title = "Video Support", description = "Preview app video on the iPhone device simply by placing your video files in the videos folder.", fontawesome_icon_name = "play-circle" },
    { title = "Automatic Icon and Metadata", description = "Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.", fontawesome_icon_name = "sync" },
    { title = "Easy to Tweak", description = "Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.", fontawesome_icon_name = "adjust" },
    { title = "Feature List", description = "Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.", fontawesome_icon_name = "star" },
    { title = "Smart App Banner", description = "Display a smart app banner on iOS devices.", fontawesome_icon_name = "arrow-alt-circle-down" },
    { title = "Social Links", description = "Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.", fontawesome_icon_name = "link" },
    { title = "FontAwesome Support", description = "Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.", fontawesome_icon_name = "info-circle" }
  ]


  # Theme Settings
  topbar_color = "#000000"
  topbar_transparency = 0.1
  topbar_title_color = "#ffffff"
  cover_image = "/images/headerimage.png"
  cover_overlay_color = "#363b3d"
  cover_overlay_transparency = 0.8
  device_color = "black"
  body_background_color = "#ffffff"
  link_color = "#1d63ea"
  app_title_color = "#ffffff"
  app_price_color = "#ffffff"
  app_description_color = "#ffffff"
  feature_title_color = "#000000"
  feature_text_color = "#666666"
  feature_icons_foreground_color = "#1d63ea"
  feature_icons_background_color = "#e6e6e6"
  social_icons_foreground_color = "#666666"
  social_icons_background_color = "#e6e6e6"
  footer_text_color = "#666666"

[build]
  ignore = ["LICENSE", "README.md", "CNAME"]
  write_stats = true
  [build.processing]
    sass = { includePaths = ["/assets/scss"], enableInlining = true }

